export type VestraEmailTemplateKey =
  | "account_creation"
  | "email_verification"
  | "password_reset"
  | "order_confirmation"
  | "payment_confirmation"
  | "shipping_update"
  | "seller_submission"
  | "authentication_status"
  | "account_notification";

export interface VestraEmailTemplate {
  key: VestraEmailTemplateKey;
  subject: string;
  preview: string;
  body: string;
}

const SIGNATURE = "Vestra\nWear the Past. Own the Future.";

export const VESTRA_EMAIL_TEMPLATES: Record<
  VestraEmailTemplateKey,
  VestraEmailTemplate
> = {
  account_creation: {
    key: "account_creation",
    subject: "Welcome to Vestra",
    preview: "Your private collector space is ready.",
    body: `Welcome to Vestra.\n\nYour private collector space is ready. Save archive pieces, review orders, and access Digital Fashion Passports from your account.\n\n${SIGNATURE}`,
  },
  email_verification: {
    key: "email_verification",
    subject: "Verify your Vestra email",
    preview: "Confirm your email address to secure your account.",
    body: `Confirm your email address to secure your Vestra account.\n\nUse the verification link provided by the configured authentication service.\n\n${SIGNATURE}`,
  },
  password_reset: {
    key: "password_reset",
    subject: "Reset your Vestra password",
    preview: "A secure password reset was requested.",
    body: `A password reset was requested for your Vestra account.\n\nUse the secure reset link provided by the configured authentication service. If you did not request this, ignore this email.\n\n${SIGNATURE}`,
  },
  order_confirmation: {
    key: "order_confirmation",
    subject: "Your Vestra order has been received",
    preview: "We have received your order.",
    body: `Your Vestra order has been received.\n\nPayment, authentication, shipping, and passport details will be populated from the production order service.\n\n${SIGNATURE}`,
  },
  payment_confirmation: {
    key: "payment_confirmation",
    subject: "Payment confirmation",
    preview: "Your payment status has been updated.",
    body: `Your Vestra payment status has been updated.\n\nFinal payment details must come from Stripe webhook verification.\n\n${SIGNATURE}`,
  },
  shipping_update: {
    key: "shipping_update",
    subject: "Shipping update from Vestra",
    preview: "Your order shipping status has changed.",
    body: `Your Vestra order shipping status has changed.\n\nCarrier, tracking, and delivery estimates must come from the configured shipping provider.\n\n${SIGNATURE}`,
  },
  seller_submission: {
    key: "seller_submission",
    subject: "Your Vestra submission was received",
    preview: "Your piece has entered review.",
    body: `Your Vestra submission was received and has entered review.\n\nAuthentication and listing status updates will be sent as the item moves through review.\n\n${SIGNATURE}`,
  },
  authentication_status: {
    key: "authentication_status",
    subject: "Authentication status update",
    preview: "A Digital Fashion Passport status has changed.",
    body: `A Vestra authentication status has changed.\n\nFinal authentication details must be supplied by Vestra's review team before a Digital Fashion Passport is issued.\n\n${SIGNATURE}`,
  },
  account_notification: {
    key: "account_notification",
    subject: "Important Vestra account notification",
    preview: "There is an important update about your account.",
    body: `There is an important update about your Vestra account.\n\nDetails must be generated by the account service.\n\n${SIGNATURE}`,
  },
};
