/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'applicantId' : string,
  'createdAt' : bigint,
  'opportunityId' : bigint,
  'message' : string,
}
export type ApplicationStatus = { 'Viewed' : null } |
  { 'Accepted' : null } |
  { 'Declined' : null } |
  { 'Pending' : null };
export interface Connection {
  'id' : bigint,
  'status' : ConnectionStatus,
  'connectedAt' : bigint,
  'receiverId' : string,
  'requesterId' : string,
}
export type ConnectionStatus = { 'Accepted' : null } |
  { 'Declined' : null } |
  { 'Pending' : null };
export interface CreateOrderInput {
  'deposit_paid' : bigint,
  'total_price' : bigint,
  'stripe_payment_id' : string,
  'order_type' : string,
  'rent_start' : [] | [Timestamp],
  'item_id' : ItemId,
  'rent_end' : [] | [Timestamp],
}
export interface DigitalPassport {
  'id' : PassportId,
  'authentication_date' : Timestamp,
  'qr_code_url' : string,
  'created_at' : Timestamp,
  'blockchain_hash' : string,
  'inspector_name' : string,
  'certificate_code' : string,
  'item_id' : ItemId,
  'condition_verified' : string,
}
export interface Item {
  'id' : ItemId,
  'status' : string,
  'price_rent_day' : [] | [bigint],
  'passport_id' : [] | [PassportId],
  'name' : string,
  'year' : bigint,
  'description' : string,
  'season' : string,
  'deposit' : [] | [bigint],
  'created_at' : Timestamp,
  'availability' : string,
  'seller_id' : UserId,
  'measurements' : string,
  'category' : string,
  'brand' : string,
  'price_buy' : [] | [bigint],
  'material' : string,
  'condition' : string,
  'images' : Array<string>,
}
export interface ItemFilter {
  'availability' : [] | [string],
  'category' : [] | [string],
  'brand' : [] | [string],
  'max_price' : [] | [bigint],
  'min_price' : [] | [bigint],
  'condition' : [] | [string],
}
export type ItemId = string;
export interface OnboardingSubmission {
  'id' : bigint,
  'experienceLevel' : string,
  'country' : string,
  'projectDescription' : string,
  'userId' : string,
  'createdAt' : bigint,
  'intent' : string,
  'industry' : string,
}
export interface Opportunity {
  'id' : bigint,
  'status' : OpportunityStatus,
  'title' : string,
  'postedBy' : string,
  'country' : string,
  'createdAt' : bigint,
  'experienceRequired' : string,
  'description' : string,
  'opportunityType' : OpportunityType,
  'applications' : Array<bigint>,
  'industry' : string,
}
export type OpportunityStatus = { 'Paused' : null } |
  { 'Active' : null } |
  { 'Filled' : null };
export type OpportunityType = { 'Job' : null } |
  { 'Startup' : null } |
  { 'Partnership' : null } |
  { 'Investment' : null } |
  { 'Freelance' : null };
export interface Order {
  'id' : OrderId,
  'status' : string,
  'deposit_paid' : bigint,
  'total_price' : bigint,
  'stripe_payment_id' : string,
  'created_at' : Timestamp,
  'order_type' : string,
  'buyer_id' : UserId,
  'rent_start' : [] | [Timestamp],
  'item_id' : ItemId,
  'rent_end' : [] | [Timestamp],
}
export type OrderId = string;
export type PassportId = string;
export interface StyleProfile {
  'id' : StyleProfileId,
  'decade' : string,
  'created_at' : Timestamp,
  'palette' : string,
  'user_id' : UserId,
  'archetype' : string,
  'occasion' : string,
}
export type StyleProfileId = string;
export interface StyleProfileInput {
  'decade' : string,
  'palette' : string,
  'archetype' : string,
  'occasion' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'member_since' : Timestamp,
  'style_profile_id' : [] | [StyleProfileId],
  'shipping_addresses' : Array<string>,
  'avatar_url' : string,
  'name' : string,
  'tier' : string,
  'created_at' : Timestamp,
  'email' : string,
  'stripe_customer_id' : string,
}
export type UserId = string;
export interface UserUpdate {
  'style_profile_id' : [] | [StyleProfileId],
  'shipping_addresses' : Array<string>,
  'avatar_url' : string,
  'name' : string,
  'tier' : string,
  'email' : string,
  'stripe_customer_id' : string,
}
export interface _SERVICE {
  'addToWishlist' : ActorMethod<[ItemId], undefined>,
  'createApplication' : ActorMethod<[bigint, string], Application>,
  'createConnection' : ActorMethod<[string], Connection>,
  'createItem' : ActorMethod<[Item], Item>,
  'createOpportunity' : ActorMethod<
    [string, string, OpportunityType, string, string, string],
    Opportunity
  >,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'createPassport' : ActorMethod<
    [
      {
        'inspector_name' : string,
        'item_id' : ItemId,
        'condition_verified' : string,
      },
    ],
    DigitalPassport
  >,
  'createUser' : ActorMethod<[string, string], User>,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getConnection' : ActorMethod<[bigint], [] | [Connection]>,
  'getConnectionsByUser' : ActorMethod<[string], Array<Connection>>,
  'getFeaturedItems' : ActorMethod<[], Array<Item>>,
  'getItem' : ActorMethod<[ItemId], [] | [Item]>,
  'getItemsByCategory' : ActorMethod<[string], Array<Item>>,
  'getItemsByFilter' : ActorMethod<[ItemFilter], Array<Item>>,
  'getOnboardingByUser' : ActorMethod<[string], [] | [OnboardingSubmission]>,
  'getOpportunitiesByCountry' : ActorMethod<[string], Array<Opportunity>>,
  'getOpportunitiesByIndustry' : ActorMethod<[string], Array<Opportunity>>,
  'getOpportunitiesByType' : ActorMethod<[OpportunityType], Array<Opportunity>>,
  'getOpportunity' : ActorMethod<[bigint], [] | [Opportunity]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getPassport' : ActorMethod<[PassportId], [] | [DigitalPassport]>,
  'getPassportByItem' : ActorMethod<[ItemId], [] | [DigitalPassport]>,
  'getStyleProfile' : ActorMethod<[], [] | [StyleProfile]>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserByPrincipal' : ActorMethod<[], [] | [User]>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getWishlist' : ActorMethod<[], Array<ItemId>>,
  'listApplicationsByOpportunity' : ActorMethod<[bigint], Array<Application>>,
  'listApplicationsByUser' : ActorMethod<[string], Array<Application>>,
  'listConnections' : ActorMethod<[], Array<Connection>>,
  'listItems' : ActorMethod<[], Array<Item>>,
  'listOpportunities' : ActorMethod<[], Array<Opportunity>>,
  'removeFromWishlist' : ActorMethod<[ItemId], undefined>,
  'saveStyleProfile' : ActorMethod<[StyleProfileInput], StyleProfile>,
  'storeAccessRequest' : ActorMethod<[string], undefined>,
  'submitOnboarding' : ActorMethod<
    [string, string, string, string, string],
    OnboardingSubmission
  >,
  'updateApplicationStatus' : ActorMethod<[bigint, ApplicationStatus], boolean>,
  'updateConnectionStatus' : ActorMethod<[bigint, ConnectionStatus], boolean>,
  'updateItemStatus' : ActorMethod<[ItemId, string], [] | [Item]>,
  'updateOpportunityStatus' : ActorMethod<[bigint, OpportunityStatus], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, string], [] | [Order]>,
  'updateUser' : ActorMethod<[UserUpdate], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];