/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemId = IDL.Text;
export const ApplicationStatus = IDL.Variant({
  'Viewed' : IDL.Null,
  'Accepted' : IDL.Null,
  'Declined' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'applicantId' : IDL.Text,
  'createdAt' : IDL.Int,
  'opportunityId' : IDL.Nat,
  'message' : IDL.Text,
});
export const ConnectionStatus = IDL.Variant({
  'Accepted' : IDL.Null,
  'Declined' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Connection = IDL.Record({
  'id' : IDL.Nat,
  'status' : ConnectionStatus,
  'connectedAt' : IDL.Int,
  'receiverId' : IDL.Text,
  'requesterId' : IDL.Text,
});
export const PassportId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserId = IDL.Text;
export const Item = IDL.Record({
  'id' : ItemId,
  'status' : IDL.Text,
  'price_rent_day' : IDL.Opt(IDL.Nat),
  'passport_id' : IDL.Opt(PassportId),
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'season' : IDL.Text,
  'deposit' : IDL.Opt(IDL.Nat),
  'created_at' : Timestamp,
  'availability' : IDL.Text,
  'seller_id' : UserId,
  'measurements' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price_buy' : IDL.Opt(IDL.Nat),
  'material' : IDL.Text,
  'condition' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const OpportunityType = IDL.Variant({
  'Job' : IDL.Null,
  'Startup' : IDL.Null,
  'Partnership' : IDL.Null,
  'Investment' : IDL.Null,
  'Freelance' : IDL.Null,
});
export const OpportunityStatus = IDL.Variant({
  'Paused' : IDL.Null,
  'Active' : IDL.Null,
  'Filled' : IDL.Null,
});
export const Opportunity = IDL.Record({
  'id' : IDL.Nat,
  'status' : OpportunityStatus,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'country' : IDL.Text,
  'createdAt' : IDL.Int,
  'experienceRequired' : IDL.Text,
  'description' : IDL.Text,
  'opportunityType' : OpportunityType,
  'applications' : IDL.Vec(IDL.Nat),
  'industry' : IDL.Text,
});
export const CreateOrderInput = IDL.Record({
  'deposit_paid' : IDL.Nat,
  'total_price' : IDL.Nat,
  'stripe_payment_id' : IDL.Text,
  'order_type' : IDL.Text,
  'rent_start' : IDL.Opt(Timestamp),
  'item_id' : ItemId,
  'rent_end' : IDL.Opt(Timestamp),
});
export const OrderId = IDL.Text;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : IDL.Text,
  'deposit_paid' : IDL.Nat,
  'total_price' : IDL.Nat,
  'stripe_payment_id' : IDL.Text,
  'created_at' : Timestamp,
  'order_type' : IDL.Text,
  'buyer_id' : UserId,
  'rent_start' : IDL.Opt(Timestamp),
  'item_id' : ItemId,
  'rent_end' : IDL.Opt(Timestamp),
});
export const DigitalPassport = IDL.Record({
  'id' : PassportId,
  'authentication_date' : Timestamp,
  'qr_code_url' : IDL.Text,
  'created_at' : Timestamp,
  'blockchain_hash' : IDL.Text,
  'inspector_name' : IDL.Text,
  'certificate_code' : IDL.Text,
  'item_id' : ItemId,
  'condition_verified' : IDL.Text,
});
export const StyleProfileId = IDL.Text;
export const User = IDL.Record({
  'id' : UserId,
  'member_since' : Timestamp,
  'style_profile_id' : IDL.Opt(StyleProfileId),
  'shipping_addresses' : IDL.Vec(IDL.Text),
  'avatar_url' : IDL.Text,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'stripe_customer_id' : IDL.Text,
});
export const ItemFilter = IDL.Record({
  'availability' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
  'max_price' : IDL.Opt(IDL.Nat),
  'min_price' : IDL.Opt(IDL.Nat),
  'condition' : IDL.Opt(IDL.Text),
});
export const OnboardingSubmission = IDL.Record({
  'id' : IDL.Nat,
  'experienceLevel' : IDL.Text,
  'country' : IDL.Text,
  'projectDescription' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : IDL.Int,
  'intent' : IDL.Text,
  'industry' : IDL.Text,
});
export const StyleProfile = IDL.Record({
  'id' : StyleProfileId,
  'decade' : IDL.Text,
  'created_at' : Timestamp,
  'palette' : IDL.Text,
  'user_id' : UserId,
  'archetype' : IDL.Text,
  'occasion' : IDL.Text,
});
export const StyleProfileInput = IDL.Record({
  'decade' : IDL.Text,
  'palette' : IDL.Text,
  'archetype' : IDL.Text,
  'occasion' : IDL.Text,
});
export const UserUpdate = IDL.Record({
  'style_profile_id' : IDL.Opt(StyleProfileId),
  'shipping_addresses' : IDL.Vec(IDL.Text),
  'avatar_url' : IDL.Text,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'email' : IDL.Text,
  'stripe_customer_id' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWishlist' : IDL.Func([ItemId], [], []),
  'createApplication' : IDL.Func([IDL.Nat, IDL.Text], [Application], []),
  'createConnection' : IDL.Func([IDL.Text], [Connection], []),
  'createItem' : IDL.Func([Item], [Item], []),
  'createOpportunity' : IDL.Func(
      [IDL.Text, IDL.Text, OpportunityType, IDL.Text, IDL.Text, IDL.Text],
      [Opportunity],
      [],
    ),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'createPassport' : IDL.Func(
      [
        IDL.Record({
          'inspector_name' : IDL.Text,
          'item_id' : ItemId,
          'condition_verified' : IDL.Text,
        }),
      ],
      [DigitalPassport],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
  'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
  'getConnection' : IDL.Func([IDL.Nat], [IDL.Opt(Connection)], ['query']),
  'getConnectionsByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Connection)],
      ['query'],
    ),
  'getFeaturedItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
  'getItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
  'getItemsByFilter' : IDL.Func([ItemFilter], [IDL.Vec(Item)], ['query']),
  'getOnboardingByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(OnboardingSubmission)],
      ['query'],
    ),
  'getOpportunitiesByCountry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'getOpportunitiesByIndustry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'getOpportunitiesByType' : IDL.Func(
      [OpportunityType],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'getOpportunity' : IDL.Func([IDL.Nat], [IDL.Opt(Opportunity)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getPassport' : IDL.Func([PassportId], [IDL.Opt(DigitalPassport)], ['query']),
  'getPassportByItem' : IDL.Func(
      [ItemId],
      [IDL.Opt(DigitalPassport)],
      ['query'],
    ),
  'getStyleProfile' : IDL.Func([], [IDL.Opt(StyleProfile)], []),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], []),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getWishlist' : IDL.Func([], [IDL.Vec(ItemId)], []),
  'listApplicationsByOpportunity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'listApplicationsByUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'listConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
  'listItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'listOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'removeFromWishlist' : IDL.Func([ItemId], [], []),
  'saveStyleProfile' : IDL.Func([StyleProfileInput], [StyleProfile], []),
  'storeAccessRequest' : IDL.Func([IDL.Text], [], []),
  'submitOnboarding' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [OnboardingSubmission],
      [],
    ),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, ApplicationStatus],
      [IDL.Bool],
      [],
    ),
  'updateConnectionStatus' : IDL.Func(
      [IDL.Nat, ConnectionStatus],
      [IDL.Bool],
      [],
    ),
  'updateItemStatus' : IDL.Func([ItemId, IDL.Text], [IDL.Opt(Item)], []),
  'updateOpportunityStatus' : IDL.Func(
      [IDL.Nat, OpportunityStatus],
      [IDL.Bool],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
  'updateUser' : IDL.Func([UserUpdate], [IDL.Opt(User)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemId = IDL.Text;
  const ApplicationStatus = IDL.Variant({
    'Viewed' : IDL.Null,
    'Accepted' : IDL.Null,
    'Declined' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'applicantId' : IDL.Text,
    'createdAt' : IDL.Int,
    'opportunityId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const ConnectionStatus = IDL.Variant({
    'Accepted' : IDL.Null,
    'Declined' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Connection = IDL.Record({
    'id' : IDL.Nat,
    'status' : ConnectionStatus,
    'connectedAt' : IDL.Int,
    'receiverId' : IDL.Text,
    'requesterId' : IDL.Text,
  });
  const PassportId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserId = IDL.Text;
  const Item = IDL.Record({
    'id' : ItemId,
    'status' : IDL.Text,
    'price_rent_day' : IDL.Opt(IDL.Nat),
    'passport_id' : IDL.Opt(PassportId),
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'season' : IDL.Text,
    'deposit' : IDL.Opt(IDL.Nat),
    'created_at' : Timestamp,
    'availability' : IDL.Text,
    'seller_id' : UserId,
    'measurements' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price_buy' : IDL.Opt(IDL.Nat),
    'material' : IDL.Text,
    'condition' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const OpportunityType = IDL.Variant({
    'Job' : IDL.Null,
    'Startup' : IDL.Null,
    'Partnership' : IDL.Null,
    'Investment' : IDL.Null,
    'Freelance' : IDL.Null,
  });
  const OpportunityStatus = IDL.Variant({
    'Paused' : IDL.Null,
    'Active' : IDL.Null,
    'Filled' : IDL.Null,
  });
  const Opportunity = IDL.Record({
    'id' : IDL.Nat,
    'status' : OpportunityStatus,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'country' : IDL.Text,
    'createdAt' : IDL.Int,
    'experienceRequired' : IDL.Text,
    'description' : IDL.Text,
    'opportunityType' : OpportunityType,
    'applications' : IDL.Vec(IDL.Nat),
    'industry' : IDL.Text,
  });
  const CreateOrderInput = IDL.Record({
    'deposit_paid' : IDL.Nat,
    'total_price' : IDL.Nat,
    'stripe_payment_id' : IDL.Text,
    'order_type' : IDL.Text,
    'rent_start' : IDL.Opt(Timestamp),
    'item_id' : ItemId,
    'rent_end' : IDL.Opt(Timestamp),
  });
  const OrderId = IDL.Text;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : IDL.Text,
    'deposit_paid' : IDL.Nat,
    'total_price' : IDL.Nat,
    'stripe_payment_id' : IDL.Text,
    'created_at' : Timestamp,
    'order_type' : IDL.Text,
    'buyer_id' : UserId,
    'rent_start' : IDL.Opt(Timestamp),
    'item_id' : ItemId,
    'rent_end' : IDL.Opt(Timestamp),
  });
  const DigitalPassport = IDL.Record({
    'id' : PassportId,
    'authentication_date' : Timestamp,
    'qr_code_url' : IDL.Text,
    'created_at' : Timestamp,
    'blockchain_hash' : IDL.Text,
    'inspector_name' : IDL.Text,
    'certificate_code' : IDL.Text,
    'item_id' : ItemId,
    'condition_verified' : IDL.Text,
  });
  const StyleProfileId = IDL.Text;
  const User = IDL.Record({
    'id' : UserId,
    'member_since' : Timestamp,
    'style_profile_id' : IDL.Opt(StyleProfileId),
    'shipping_addresses' : IDL.Vec(IDL.Text),
    'avatar_url' : IDL.Text,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'stripe_customer_id' : IDL.Text,
  });
  const ItemFilter = IDL.Record({
    'availability' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
    'max_price' : IDL.Opt(IDL.Nat),
    'min_price' : IDL.Opt(IDL.Nat),
    'condition' : IDL.Opt(IDL.Text),
  });
  const OnboardingSubmission = IDL.Record({
    'id' : IDL.Nat,
    'experienceLevel' : IDL.Text,
    'country' : IDL.Text,
    'projectDescription' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : IDL.Int,
    'intent' : IDL.Text,
    'industry' : IDL.Text,
  });
  const StyleProfile = IDL.Record({
    'id' : StyleProfileId,
    'decade' : IDL.Text,
    'created_at' : Timestamp,
    'palette' : IDL.Text,
    'user_id' : UserId,
    'archetype' : IDL.Text,
    'occasion' : IDL.Text,
  });
  const StyleProfileInput = IDL.Record({
    'decade' : IDL.Text,
    'palette' : IDL.Text,
    'archetype' : IDL.Text,
    'occasion' : IDL.Text,
  });
  const UserUpdate = IDL.Record({
    'style_profile_id' : IDL.Opt(StyleProfileId),
    'shipping_addresses' : IDL.Vec(IDL.Text),
    'avatar_url' : IDL.Text,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'email' : IDL.Text,
    'stripe_customer_id' : IDL.Text,
  });
  
  return IDL.Service({
    'addToWishlist' : IDL.Func([ItemId], [], []),
    'createApplication' : IDL.Func([IDL.Nat, IDL.Text], [Application], []),
    'createConnection' : IDL.Func([IDL.Text], [Connection], []),
    'createItem' : IDL.Func([Item], [Item], []),
    'createOpportunity' : IDL.Func(
        [IDL.Text, IDL.Text, OpportunityType, IDL.Text, IDL.Text, IDL.Text],
        [Opportunity],
        [],
      ),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'createPassport' : IDL.Func(
        [
          IDL.Record({
            'inspector_name' : IDL.Text,
            'item_id' : ItemId,
            'condition_verified' : IDL.Text,
          }),
        ],
        [DigitalPassport],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [User], []),
    'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
    'getConnection' : IDL.Func([IDL.Nat], [IDL.Opt(Connection)], ['query']),
    'getConnectionsByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Connection)],
        ['query'],
      ),
    'getFeaturedItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
    'getItemsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Item)], ['query']),
    'getItemsByFilter' : IDL.Func([ItemFilter], [IDL.Vec(Item)], ['query']),
    'getOnboardingByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(OnboardingSubmission)],
        ['query'],
      ),
    'getOpportunitiesByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'getOpportunitiesByIndustry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'getOpportunitiesByType' : IDL.Func(
        [OpportunityType],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'getOpportunity' : IDL.Func([IDL.Nat], [IDL.Opt(Opportunity)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getPassport' : IDL.Func(
        [PassportId],
        [IDL.Opt(DigitalPassport)],
        ['query'],
      ),
    'getPassportByItem' : IDL.Func(
        [ItemId],
        [IDL.Opt(DigitalPassport)],
        ['query'],
      ),
    'getStyleProfile' : IDL.Func([], [IDL.Opt(StyleProfile)], []),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserByPrincipal' : IDL.Func([], [IDL.Opt(User)], []),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getWishlist' : IDL.Func([], [IDL.Vec(ItemId)], []),
    'listApplicationsByOpportunity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'listApplicationsByUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'listConnections' : IDL.Func([], [IDL.Vec(Connection)], ['query']),
    'listItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'listOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'removeFromWishlist' : IDL.Func([ItemId], [], []),
    'saveStyleProfile' : IDL.Func([StyleProfileInput], [StyleProfile], []),
    'storeAccessRequest' : IDL.Func([IDL.Text], [], []),
    'submitOnboarding' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [OnboardingSubmission],
        [],
      ),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, ApplicationStatus],
        [IDL.Bool],
        [],
      ),
    'updateConnectionStatus' : IDL.Func(
        [IDL.Nat, ConnectionStatus],
        [IDL.Bool],
        [],
      ),
    'updateItemStatus' : IDL.Func([ItemId, IDL.Text], [IDL.Opt(Item)], []),
    'updateOpportunityStatus' : IDL.Func(
        [IDL.Nat, OpportunityStatus],
        [IDL.Bool],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
    'updateUser' : IDL.Func([UserUpdate], [IDL.Opt(User)], []),
  });
};

export const init = ({ IDL }) => { return []; };