/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type StyleProfileId = string;
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    applicantId: string;
    createdAt: bigint;
    opportunityId: bigint;
    message: string;
}
export interface User {
    id: UserId;
    member_since: Timestamp;
    style_profile_id?: StyleProfileId;
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    created_at: Timestamp;
    email: string;
    stripe_customer_id: string;
}
export interface ItemFilter {
    availability?: string;
    category?: string;
    brand?: string;
    max_price?: bigint;
    min_price?: bigint;
    condition?: string;
}
export interface OnboardingSubmission {
    id: bigint;
    experienceLevel: string;
    country: string;
    projectDescription: string;
    userId: string;
    createdAt: bigint;
    intent: string;
    industry: string;
}
export interface Order {
    id: OrderId;
    status: string;
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    created_at: Timestamp;
    order_type: string;
    buyer_id: UserId;
    rent_start?: Timestamp;
    item_id: ItemId;
    rent_end?: Timestamp;
}
export interface Opportunity {
    id: bigint;
    status: OpportunityStatus;
    title: string;
    postedBy: string;
    country: string;
    createdAt: bigint;
    experienceRequired: string;
    description: string;
    opportunityType: OpportunityType;
    applications: Array<bigint>;
    industry: string;
}
export type UserId = string;
export interface Item {
    id: ItemId;
    status: string;
    price_rent_day?: bigint;
    passport_id?: PassportId;
    name: string;
    year: bigint;
    description: string;
    season: string;
    deposit?: bigint;
    created_at: Timestamp;
    availability: string;
    seller_id: UserId;
    measurements: string;
    category: string;
    brand: string;
    price_buy?: bigint;
    material: string;
    condition: string;
    images: Array<string>;
}
export interface StyleProfile {
    id: StyleProfileId;
    decade: string;
    created_at: Timestamp;
    palette: string;
    user_id: UserId;
    archetype: string;
    occasion: string;
}
export type ItemId = string;
export interface DigitalPassport {
    id: PassportId;
    authentication_date: Timestamp;
    qr_code_url: string;
    created_at: Timestamp;
    blockchain_hash: string;
    inspector_name: string;
    certificate_code: string;
    item_id: ItemId;
    condition_verified: string;
}
export interface UserUpdate {
    style_profile_id?: StyleProfileId;
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    email: string;
    stripe_customer_id: string;
}
export interface CreateOrderInput {
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    order_type: string;
    rent_start?: Timestamp;
    item_id: ItemId;
    rent_end?: Timestamp;
}
export type PassportId = string;
export interface StyleProfileInput {
    decade: string;
    palette: string;
    archetype: string;
    occasion: string;
}
export interface Connection {
    id: bigint;
    status: ConnectionStatus;
    connectedAt: bigint;
    receiverId: string;
    requesterId: string;
}
export type OrderId = string;
export enum ApplicationStatus {
    Viewed = "Viewed",
    Accepted = "Accepted",
    Declined = "Declined",
    Pending = "Pending"
}
export enum ConnectionStatus {
    Accepted = "Accepted",
    Declined = "Declined",
    Pending = "Pending"
}
export enum OpportunityStatus {
    Paused = "Paused",
    Active = "Active",
    Filled = "Filled"
}
export enum OpportunityType {
    Job = "Job",
    Startup = "Startup",
    Partnership = "Partnership",
    Investment = "Investment",
    Freelance = "Freelance"
}
export interface backendInterface {
    addToWishlist(item_id: ItemId): Promise<void>;
    createApplication(opportunityId: bigint, message: string): Promise<Application>;
    createConnection(receiverId: string): Promise<Connection>;
    createItem(item: Item): Promise<Item>;
    createOpportunity(title: string, description: string, opportunityType: OpportunityType, country: string, industry: string, experienceRequired: string): Promise<Opportunity>;
    createOrder(input: CreateOrderInput): Promise<Order>;
    createPassport(input: {
        inspector_name: string;
        item_id: ItemId;
        condition_verified: string;
    }): Promise<DigitalPassport>;
    createUser(name: string, email: string): Promise<User>;
    getApplication(id: bigint): Promise<Application | null>;
    getConnection(id: bigint): Promise<Connection | null>;
    getConnectionsByUser(userId: string): Promise<Array<Connection>>;
    getFeaturedItems(): Promise<Array<Item>>;
    getItem(id: ItemId): Promise<Item | null>;
    getItemsByCategory(category: string): Promise<Array<Item>>;
    getItemsByFilter(filter: ItemFilter): Promise<Array<Item>>;
    getOnboardingByUser(userId: string): Promise<OnboardingSubmission | null>;
    getOpportunitiesByCountry(country: string): Promise<Array<Opportunity>>;
    getOpportunitiesByIndustry(industry: string): Promise<Array<Opportunity>>;
    getOpportunitiesByType(opportunityType: OpportunityType): Promise<Array<Opportunity>>;
    getOpportunity(id: bigint): Promise<Opportunity | null>;
    getOrder(id: OrderId): Promise<Order | null>;
    getPassport(id: PassportId): Promise<DigitalPassport | null>;
    getPassportByItem(item_id: ItemId): Promise<DigitalPassport | null>;
    getStyleProfile(): Promise<StyleProfile | null>;
    getUser(id: UserId): Promise<User | null>;
    getUserByPrincipal(): Promise<User | null>;
    getUserOrders(): Promise<Array<Order>>;
    getWishlist(): Promise<Array<ItemId>>;
    listApplicationsByOpportunity(opportunityId: bigint): Promise<Array<Application>>;
    listApplicationsByUser(applicantId: string): Promise<Array<Application>>;
    listConnections(): Promise<Array<Connection>>;
    listItems(): Promise<Array<Item>>;
    listOpportunities(): Promise<Array<Opportunity>>;
    removeFromWishlist(item_id: ItemId): Promise<void>;
    saveStyleProfile(input: StyleProfileInput): Promise<StyleProfile>;
    storeAccessRequest(email: string): Promise<void>;
    submitOnboarding(country: string, intent: string, industry: string, experienceLevel: string, projectDescription: string): Promise<OnboardingSubmission>;
    updateApplicationStatus(id: bigint, status: ApplicationStatus): Promise<boolean>;
    updateConnectionStatus(id: bigint, status: ConnectionStatus): Promise<boolean>;
    updateItemStatus(id: ItemId, status: string): Promise<Item | null>;
    updateOpportunityStatus(id: bigint, status: OpportunityStatus): Promise<boolean>;
    updateOrderStatus(id: OrderId, status: string): Promise<Order | null>;
    updateUser(update: UserUpdate): Promise<User | null>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, Connection as _Connection, ConnectionStatus as _ConnectionStatus, CreateOrderInput as _CreateOrderInput, DigitalPassport as _DigitalPassport, Item as _Item, ItemFilter as _ItemFilter, ItemId as _ItemId, OnboardingSubmission as _OnboardingSubmission, Opportunity as _Opportunity, OpportunityStatus as _OpportunityStatus, OpportunityType as _OpportunityType, Order as _Order, OrderId as _OrderId, PassportId as _PassportId, StyleProfile as _StyleProfile, StyleProfileId as _StyleProfileId, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserUpdate as _UserUpdate } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWishlist(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async createApplication(arg0: bigint, arg1: string): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplication(arg0, arg1);
                return from_candid_Application_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplication(arg0, arg1);
            return from_candid_Application_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createConnection(arg0: string): Promise<Connection> {
        if (this.processError) {
            try {
                const result = await this.actor.createConnection(arg0);
                return from_candid_Connection_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConnection(arg0);
            return from_candid_Connection_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createItem(arg0: Item): Promise<Item> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(to_candid_Item_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Item_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(to_candid_Item_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Item_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOpportunity(arg0: string, arg1: string, arg2: OpportunityType, arg3: string, arg4: string, arg5: string): Promise<Opportunity> {
        if (this.processError) {
            try {
                const result = await this.actor.createOpportunity(arg0, arg1, to_candid_OpportunityType_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return from_candid_Opportunity_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOpportunity(arg0, arg1, to_candid_OpportunityType_n15(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return from_candid_Opportunity_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: CreateOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPassport(arg0: {
        inspector_name: string;
        item_id: ItemId;
        condition_verified: string;
    }): Promise<DigitalPassport> {
        if (this.processError) {
            try {
                const result = await this.actor.createPassport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPassport(arg0);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return from_candid_User_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplication(arg0: bigint): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplication(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplication(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnection(arg0: bigint): Promise<Connection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnection(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnection(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConnectionsByUser(arg0: string): Promise<Array<Connection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionsByUser(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionsByUser(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedItems();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedItems();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: ItemId): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByCategory(arg0: string): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByCategory(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByCategory(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemsByFilter(arg0: ItemFilter): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemsByFilter(to_candid_ItemFilter_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemsByFilter(to_candid_ItemFilter_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingByUser(arg0: string): Promise<OnboardingSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingByUser(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingByUser(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunitiesByCountry(arg0: string): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunitiesByCountry(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunitiesByCountry(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunitiesByIndustry(arg0: string): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunitiesByIndustry(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunitiesByIndustry(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunitiesByType(arg0: OpportunityType): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunitiesByType(to_candid_OpportunityType_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunitiesByType(to_candid_OpportunityType_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunity(arg0: bigint): Promise<Opportunity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunity(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunity(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassport(arg0: PassportId): Promise<DigitalPassport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassport(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassport(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPassportByItem(arg0: ItemId): Promise<DigitalPassport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassportByItem(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassportByItem(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStyleProfile(): Promise<StyleProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStyleProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStyleProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByPrincipal(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByPrincipal();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByPrincipal();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<ItemId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async listApplicationsByOpportunity(arg0: bigint): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsByOpportunity(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsByOpportunity(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApplicationsByUser(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsByUser(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsByUser(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listConnections(): Promise<Array<Connection>> {
        if (this.processError) {
            try {
                const result = await this.actor.listConnections();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listConnections();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItems();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItems();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOpportunities(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOpportunities();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOpportunities();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: ItemId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async saveStyleProfile(arg0: StyleProfileInput): Promise<StyleProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStyleProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStyleProfile(arg0);
            return result;
        }
    }
    async storeAccessRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeAccessRequest(arg0);
            return result;
        }
    }
    async submitOnboarding(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<OnboardingSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitOnboarding(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitOnboarding(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateConnectionStatus(arg0: bigint, arg1: ConnectionStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateConnectionStatus(arg0, to_candid_ConnectionStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateConnectionStatus(arg0, to_candid_ConnectionStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateItemStatus(arg0: ItemId, arg1: string): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItemStatus(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItemStatus(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOpportunityStatus(arg0: bigint, arg1: OpportunityStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOpportunityStatus(arg0, to_candid_OpportunityStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOpportunityStatus(arg0, to_candid_OpportunityStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: UserUpdate): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(to_candid_UserUpdate_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(to_candid_UserUpdate_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApplicationStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ConnectionStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConnectionStatus): ConnectionStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Connection_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Connection): Connection {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_OpportunityStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpportunityStatus): OpportunityStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_OpportunityType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpportunityType): OpportunityType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Opportunity_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Opportunity): Opportunity {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_User_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PassportId]): PassportId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StyleProfileId]): StyleProfileId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Application]): Application | null {
    return value.length === 0 ? null : from_candid_Application_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Connection]): Connection | null {
    return value.length === 0 ? null : from_candid_Connection_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OnboardingSubmission]): OnboardingSubmission | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Opportunity]): Opportunity | null {
    return value.length === 0 ? null : from_candid_Opportunity_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DigitalPassport]): DigitalPassport | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StyleProfile]): StyleProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    status: string;
    price_rent_day: [] | [bigint];
    passport_id: [] | [_PassportId];
    name: string;
    year: bigint;
    description: string;
    season: string;
    deposit: [] | [bigint];
    created_at: _Timestamp;
    availability: string;
    seller_id: _UserId;
    measurements: string;
    category: string;
    brand: string;
    price_buy: [] | [bigint];
    material: string;
    condition: string;
    images: Array<string>;
}): {
    id: ItemId;
    status: string;
    price_rent_day?: bigint;
    passport_id?: PassportId;
    name: string;
    year: bigint;
    description: string;
    season: string;
    deposit?: bigint;
    created_at: Timestamp;
    availability: string;
    seller_id: UserId;
    measurements: string;
    category: string;
    brand: string;
    price_buy?: bigint;
    material: string;
    condition: string;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: value.status,
        price_rent_day: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.price_rent_day)),
        passport_id: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.passport_id)),
        name: value.name,
        year: value.year,
        description: value.description,
        season: value.season,
        deposit: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.deposit)),
        created_at: value.created_at,
        availability: value.availability,
        seller_id: value.seller_id,
        measurements: value.measurements,
        category: value.category,
        brand: value.brand,
        price_buy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.price_buy)),
        material: value.material,
        condition: value.condition,
        images: value.images
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OpportunityStatus;
    title: string;
    postedBy: string;
    country: string;
    createdAt: bigint;
    experienceRequired: string;
    description: string;
    opportunityType: _OpportunityType;
    applications: Array<bigint>;
    industry: string;
}): {
    id: bigint;
    status: OpportunityStatus;
    title: string;
    postedBy: string;
    country: string;
    createdAt: bigint;
    experienceRequired: string;
    description: string;
    opportunityType: OpportunityType;
    applications: Array<bigint>;
    industry: string;
} {
    return {
        id: value.id,
        status: from_candid_OpportunityStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        postedBy: value.postedBy,
        country: value.country,
        createdAt: value.createdAt,
        experienceRequired: value.experienceRequired,
        description: value.description,
        opportunityType: from_candid_OpportunityType_n21(_uploadFile, _downloadFile, value.opportunityType),
        applications: value.applications,
        industry: value.industry
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    applicantId: string;
    createdAt: bigint;
    opportunityId: bigint;
    message: string;
}): {
    id: bigint;
    status: ApplicationStatus;
    applicantId: string;
    createdAt: bigint;
    opportunityId: bigint;
    message: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n3(_uploadFile, _downloadFile, value.status),
        applicantId: value.applicantId,
        createdAt: value.createdAt,
        opportunityId: value.opportunityId,
        message: value.message
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: string;
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    created_at: _Timestamp;
    order_type: string;
    buyer_id: _UserId;
    rent_start: [] | [_Timestamp];
    item_id: _ItemId;
    rent_end: [] | [_Timestamp];
}): {
    id: OrderId;
    status: string;
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    created_at: Timestamp;
    order_type: string;
    buyer_id: UserId;
    rent_start?: Timestamp;
    item_id: ItemId;
    rent_end?: Timestamp;
} {
    return {
        id: value.id,
        status: value.status,
        deposit_paid: value.deposit_paid,
        total_price: value.total_price,
        stripe_payment_id: value.stripe_payment_id,
        created_at: value.created_at,
        order_type: value.order_type,
        buyer_id: value.buyer_id,
        rent_start: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.rent_start)),
        item_id: value.item_id,
        rent_end: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.rent_end))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    member_since: _Timestamp;
    style_profile_id: [] | [_StyleProfileId];
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    created_at: _Timestamp;
    email: string;
    stripe_customer_id: string;
}): {
    id: UserId;
    member_since: Timestamp;
    style_profile_id?: StyleProfileId;
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    created_at: Timestamp;
    email: string;
    stripe_customer_id: string;
} {
    return {
        id: value.id,
        member_since: value.member_since,
        style_profile_id: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.style_profile_id)),
        shipping_addresses: value.shipping_addresses,
        avatar_url: value.avatar_url,
        name: value.name,
        tier: value.tier,
        created_at: value.created_at,
        email: value.email,
        stripe_customer_id: value.stripe_customer_id
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ConnectionStatus;
    connectedAt: bigint;
    receiverId: string;
    requesterId: string;
}): {
    id: bigint;
    status: ConnectionStatus;
    connectedAt: bigint;
    receiverId: string;
    requesterId: string;
} {
    return {
        id: value.id,
        status: from_candid_ConnectionStatus_n7(_uploadFile, _downloadFile, value.status),
        connectedAt: value.connectedAt,
        receiverId: value.receiverId,
        requesterId: value.requesterId
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paused: null;
} | {
    Active: null;
} | {
    Filled: null;
}): OpportunityStatus {
    return "Paused" in value ? OpportunityStatus.Paused : "Active" in value ? OpportunityStatus.Active : "Filled" in value ? OpportunityStatus.Filled : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Job: null;
} | {
    Startup: null;
} | {
    Partnership: null;
} | {
    Investment: null;
} | {
    Freelance: null;
}): OpportunityType {
    return "Job" in value ? OpportunityType.Job : "Startup" in value ? OpportunityType.Startup : "Partnership" in value ? OpportunityType.Partnership : "Investment" in value ? OpportunityType.Investment : "Freelance" in value ? OpportunityType.Freelance : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewed: null;
} | {
    Accepted: null;
} | {
    Declined: null;
} | {
    Pending: null;
}): ApplicationStatus {
    return "Viewed" in value ? ApplicationStatus.Viewed : "Accepted" in value ? ApplicationStatus.Accepted : "Declined" in value ? ApplicationStatus.Declined : "Pending" in value ? ApplicationStatus.Pending : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Accepted: null;
} | {
    Declined: null;
} | {
    Pending: null;
}): ConnectionStatus {
    return "Accepted" in value ? ConnectionStatus.Accepted : "Declined" in value ? ConnectionStatus.Declined : "Pending" in value ? ConnectionStatus.Pending : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Connection>): Array<Connection> {
    return value.map((x)=>from_candid_Connection_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Opportunity>): Array<Opportunity> {
    return value.map((x)=>from_candid_Opportunity_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n1(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ConnectionStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConnectionStatus): _ConnectionStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderInput): _CreateOrderInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ItemFilter_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemFilter): _ItemFilter {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Item_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Item): _Item {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityStatus): _OpportunityStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityType): _OpportunityType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserUpdate_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserUpdate): _UserUpdate {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ItemId;
    status: string;
    price_rent_day?: bigint;
    passport_id?: PassportId;
    name: string;
    year: bigint;
    description: string;
    season: string;
    deposit?: bigint;
    created_at: Timestamp;
    availability: string;
    seller_id: UserId;
    measurements: string;
    category: string;
    brand: string;
    price_buy?: bigint;
    material: string;
    condition: string;
    images: Array<string>;
}): {
    id: _ItemId;
    status: string;
    price_rent_day: [] | [bigint];
    passport_id: [] | [_PassportId];
    name: string;
    year: bigint;
    description: string;
    season: string;
    deposit: [] | [bigint];
    created_at: _Timestamp;
    availability: string;
    seller_id: _UserId;
    measurements: string;
    category: string;
    brand: string;
    price_buy: [] | [bigint];
    material: string;
    condition: string;
    images: Array<string>;
} {
    return {
        id: value.id,
        status: value.status,
        price_rent_day: value.price_rent_day ? candid_some(value.price_rent_day) : candid_none(),
        passport_id: value.passport_id ? candid_some(value.passport_id) : candid_none(),
        name: value.name,
        year: value.year,
        description: value.description,
        season: value.season,
        deposit: value.deposit ? candid_some(value.deposit) : candid_none(),
        created_at: value.created_at,
        availability: value.availability,
        seller_id: value.seller_id,
        measurements: value.measurements,
        category: value.category,
        brand: value.brand,
        price_buy: value.price_buy ? candid_some(value.price_buy) : candid_none(),
        material: value.material,
        condition: value.condition,
        images: value.images
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    order_type: string;
    rent_start?: Timestamp;
    item_id: ItemId;
    rent_end?: Timestamp;
}): {
    deposit_paid: bigint;
    total_price: bigint;
    stripe_payment_id: string;
    order_type: string;
    rent_start: [] | [_Timestamp];
    item_id: _ItemId;
    rent_end: [] | [_Timestamp];
} {
    return {
        deposit_paid: value.deposit_paid,
        total_price: value.total_price,
        stripe_payment_id: value.stripe_payment_id,
        order_type: value.order_type,
        rent_start: value.rent_start ? candid_some(value.rent_start) : candid_none(),
        item_id: value.item_id,
        rent_end: value.rent_end ? candid_some(value.rent_end) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    availability?: string;
    category?: string;
    brand?: string;
    max_price?: bigint;
    min_price?: bigint;
    condition?: string;
}): {
    availability: [] | [string];
    category: [] | [string];
    brand: [] | [string];
    max_price: [] | [bigint];
    min_price: [] | [bigint];
    condition: [] | [string];
} {
    return {
        availability: value.availability ? candid_some(value.availability) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        max_price: value.max_price ? candid_some(value.max_price) : candid_none(),
        min_price: value.min_price ? candid_some(value.min_price) : candid_none(),
        condition: value.condition ? candid_some(value.condition) : candid_none()
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    style_profile_id?: StyleProfileId;
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    email: string;
    stripe_customer_id: string;
}): {
    style_profile_id: [] | [_StyleProfileId];
    shipping_addresses: Array<string>;
    avatar_url: string;
    name: string;
    tier: string;
    email: string;
    stripe_customer_id: string;
} {
    return {
        style_profile_id: value.style_profile_id ? candid_some(value.style_profile_id) : candid_none(),
        shipping_addresses: value.shipping_addresses,
        avatar_url: value.avatar_url,
        name: value.name,
        tier: value.tier,
        email: value.email,
        stripe_customer_id: value.stripe_customer_id
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityType): {
    Job: null;
} | {
    Startup: null;
} | {
    Partnership: null;
} | {
    Investment: null;
} | {
    Freelance: null;
} {
    return value == OpportunityType.Job ? {
        Job: null
    } : value == OpportunityType.Startup ? {
        Startup: null
    } : value == OpportunityType.Partnership ? {
        Partnership: null
    } : value == OpportunityType.Investment ? {
        Investment: null
    } : value == OpportunityType.Freelance ? {
        Freelance: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    Viewed: null;
} | {
    Accepted: null;
} | {
    Declined: null;
} | {
    Pending: null;
} {
    return value == ApplicationStatus.Viewed ? {
        Viewed: null
    } : value == ApplicationStatus.Accepted ? {
        Accepted: null
    } : value == ApplicationStatus.Declined ? {
        Declined: null
    } : value == ApplicationStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConnectionStatus): {
    Accepted: null;
} | {
    Declined: null;
} | {
    Pending: null;
} {
    return value == ConnectionStatus.Accepted ? {
        Accepted: null
    } : value == ConnectionStatus.Declined ? {
        Declined: null
    } : value == ConnectionStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityStatus): {
    Paused: null;
} | {
    Active: null;
} | {
    Filled: null;
} {
    return value == OpportunityStatus.Paused ? {
        Paused: null
    } : value == OpportunityStatus.Active ? {
        Active: null
    } : value == OpportunityStatus.Filled ? {
        Filled: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
